// Generated by CoffeeScript 1.7.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/employee/getEmployee/:name', function(req, res) {
    var address, employee, name;
    res.type('application/json');
    name = req.params.name;
    console.log("Parameter: " + name);
    employee = new Object();
    employee.name = req.params.name;
    employee.age = 25;
    employee.deparment = "HR";
    employee.wage = 15000.00;
    address = new Object();
    address.city = "Massachusetts";
    address.state = "Springfield";
    address.street = "Evergreen";
    address.zip = 66450;
    employee.address = address;
    return res.json(employee);
  });

  app.post('/employee/postEmployee', function(req, res) {
    var employee;
    employee = req.body;
    console.log("Got request: " + JSON.stringify(employee));
    return res.send(employee);
  });

  app.listen(process.env.PORT || 9999);

}).call(this);

//# sourceMappingURL=webservice.map
